#
# To run:
# docker-compose up -d
#
# To stop and cleanup:
# docker-compose stop && docker-compose rm -vf
#

version: '3.5'
services:

    postgres:
        image: postgres:11.4
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=proto
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password

    golang-tests:
        image: golang:1.12-stretch
        entrypoint: /bin/bash
        command:
            - "-cexu"
            - "go get -u github.com/kisielk/errcheck && go build -i -o /go/bin/cover cmd/cover && go build -i -o /go/bin/errcheck github.com/kisielk/errcheck && errcheck github.com/veqryn/protobuf/ptypes/... && go test -a -race github.com/veqryn/protobuf/ptypes/..."
        volumes:
            - ".:/go/src/github.com/veqryn/protobuf:ro"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_NAME=proto
        depends_on:
            - postgres
